/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.consultas;
import Controlador.documento;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itzim
 */
public class actividadActualAlumno extends javax.swing.JFrame {

    private consultas consultar;
    private login metodo;
    private documento documento;
    
    
    public actividadActualAlumno() {
        initComponents();
        setLocationRelativeTo(null);
        consultar = new consultas();
        metodo = new login();
        documento = new documento();
        consultar.actividadActual(actividadActual, metodo.ncontrol);
        bajaActividad.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cccc2 = new javax.swing.JLabel();
        bajaActividad = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        volver3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actividadActual = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MI ACTIVIDAD ACTUAL");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 948, 73));

        cccc2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        cccc2.setForeground(new java.awt.Color(51, 51, 51));
        cccc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cccc2.setText("DESCARGAR HORARIO");
        cccc2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cccc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cccc2MouseClicked(evt);
            }
        });
        jPanel1.add(cccc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 210, 34));

        bajaActividad.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        bajaActividad.setForeground(new java.awt.Color(51, 51, 51));
        bajaActividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bajaActividad.setText("DAR ACTIVIDAD DE BAJA");
        bajaActividad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bajaActividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajaActividadMouseClicked(evt);
            }
        });
        jPanel1.add(bajaActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 210, 34));

        volver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 0, 153));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 60, -1));

        volver3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver3.setForeground(new java.awt.Color(0, 0, 153));
        volver3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        volver3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volver3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volver3MouseExited(evt);
            }
        });
        jPanel1.add(volver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 60, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        actividadActual.setBackground(new java.awt.Color(255, 255, 255));
        actividadActual.setForeground(new java.awt.Color(51, 51, 51));
        actividadActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE DE LA ACTIVIDAD", "HORARIO", "CREDITOS", "DOCENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        actividadActual.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        actividadActual.setColorBordeFilas(new java.awt.Color(51, 51, 51));
        actividadActual.setColorBordeHead(new java.awt.Color(51, 51, 51));
        actividadActual.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        actividadActual.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        actividadActual.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        actividadActual.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        actividadActual.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        actividadActual.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        actividadActual.setFuenteFilas(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        actividadActual.setFuenteFilasSelect(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        actividadActual.setFuenteHead(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        actividadActual.setGridColor(new java.awt.Color(51, 51, 51));
        actividadActual.setRowHeight(50);
        actividadActual.setRowSelectionAllowed(false);
        actividadActual.getTableHeader().setResizingAllowed(false);
        actividadActual.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(actividadActual);
        if (actividadActual.getColumnModel().getColumnCount() > 0) {
            actividadActual.getColumnModel().getColumn(0).setResizable(false);
            actividadActual.getColumnModel().getColumn(0).setPreferredWidth(80);
            actividadActual.getColumnModel().getColumn(1).setResizable(false);
            actividadActual.getColumnModel().getColumn(1).setPreferredWidth(10);
            actividadActual.getColumnModel().getColumn(2).setResizable(false);
            actividadActual.getColumnModel().getColumn(2).setPreferredWidth(10);
            actividadActual.getColumnModel().getColumn(3).setResizable(false);
            actividadActual.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 890, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        menuAlumno ventana  = new menuAlumno();   
        ventana.setVisible(true);
        this.dispose();
        consultar.inscrito=true;
    }//GEN-LAST:event_volverMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setFont(new Font("Roboto", Font.PLAIN, 14));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setFont(new Font("Roboto", Font.PLAIN, 12));
    }//GEN-LAST:event_volverMouseExited

    private void bajaActividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajaActividadMouseClicked
        consultar.bajaActividad(metodo.ncontrol);
        consultar.inscrito=false;
        menuAlumno ventana  = new menuAlumno();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bajaActividadMouseClicked

    private void volver3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver3MouseClicked
        menuAlumno ventana  = new menuAlumno();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volver3MouseClicked

    private void volver3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver3MouseEntered
        volver.setFont(new Font("Roboto", Font.PLAIN, 14));
    }//GEN-LAST:event_volver3MouseEntered

    private void volver3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver3MouseExited
        volver.setFont(new Font("Roboto", Font.PLAIN, 12));
    }//GEN-LAST:event_volver3MouseExited

    private void cccc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cccc2MouseClicked
        String userHome = System.getProperty("user.home");
        String array[] = new String[5];
        String[] actual =new String[4];
        actual=consultar.actividadActual2( login.ncontrol);
        array=consultar.seleccionarAlumno(login.ncontrol);
        documento.generar_horario(userHome+"/Downloads/Horario-"+array[0]+" "+array[1]+" "+array[2] +".pdf",login.ncontrol,array[0],array[1],array[2],array[3],Integer.parseInt(array[4]),Integer.parseInt(actual[2]),actual[0],actual[4],actual[3],actual[1]);
        //para guardar en la ruta del proyecto documento.generar_horario("Horario-"+array[0]+" "+array[1]+" "+array[2] +".pdf",login.ncontrol,array[0],array[1],array[2],array[3],Integer.parseInt(array[4]),Integer.parseInt(actual[2]),actual[0],actual[5],actual[4],actual[3],actual[1]);
        JOptionPane.showMessageDialog(null, "Horario descargado correctamente");
    }//GEN-LAST:event_cccc2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actividadActualAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actividadActualAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actividadActualAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actividadActualAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actividadActualAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro actividadActual;
    private javax.swing.JLabel bajaActividad;
    private javax.swing.JLabel cccc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel volver;
    private javax.swing.JLabel volver3;
    // End of variables declaration//GEN-END:variables
}
