/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.consultas;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itzim
 */
public class agregarActividad extends javax.swing.JFrame {

    private consultas consultar;
    private gestionarActividades metodo;
    static String clave,nombre,horario,requisitos,lugar, cupo,docente,departamento,creditos,aux;
    public agregarActividad(String clave, String nombre, String horario, String requisitos, String lugar, String cupo, String docente, String departamento, String creditos, String aux) {
        initComponents();
        setLocationRelativeTo(null);
        consultar = new consultas();
        metodo = new gestionarActividades();
        if(metodo.accion=="agregar"){
            modificar.setVisible(false);
        }else{
            agregar.setVisible(false);
        }
        this.aux=aux;
        txtcupo.setText(""+cupo);
        txtclave.setText(clave);
        txtnombre.setText(nombre);
        txthorario.setText(horario);
        txtdocente.setText(""+docente);
        txtdepartamento.setText(""+departamento);
        txtcreditos.setText(""+creditos);
        txtrequisitos.setText(requisitos);
        txtlugar.setText(lugar);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        volver1 = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        txtcupo = new componentes.TextField();
        txtclave = new componentes.TextField();
        txtnombre = new componentes.TextField();
        txthorario = new componentes.TextField();
        txtdocente = new componentes.TextField();
        txtdepartamento = new componentes.TextField();
        txtcreditos = new componentes.TextField();
        txtrequisitos = new componentes.TextField();
        txtlugar = new componentes.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTIONAR ACTIVIDADES");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 750, 50));

        volver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 0, 153));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        volver1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver1.setForeground(new java.awt.Color(0, 0, 153));
        volver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver1.setText("VOLVER");
        volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volver1MouseExited(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, -1));

        agregar.setBackground(new java.awt.Color(51, 51, 255));
        agregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregar.setText("AGREGAR ACTIVIDAD");
        agregar.setOpaque(true);
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 170, 40));

        modificar.setBackground(new java.awt.Color(51, 51, 255));
        modificar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificar.setText("MODIFICAR DATOS DE ACTIVIDAD");
        modificar.setOpaque(true);
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 210, 40));

        txtcupo.setBackground(new java.awt.Color(255, 255, 255));
        txtcupo.setForeground(new java.awt.Color(51, 51, 51));
        txtcupo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtcupo.setLabelText("CUPO");
        txtcupo.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtcupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 110, -1));

        txtclave.setBackground(new java.awt.Color(255, 255, 255));
        txtclave.setForeground(new java.awt.Color(51, 51, 51));
        txtclave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtclave.setLabelText("CLAVE GRUPO");
        txtclave.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, -1));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setForeground(new java.awt.Color(51, 51, 51));
        txtnombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtnombre.setLabelText("NOMBRE DE LA ACTIVIDAD");
        txtnombre.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, -1));

        txthorario.setBackground(new java.awt.Color(255, 255, 255));
        txthorario.setForeground(new java.awt.Color(51, 51, 51));
        txthorario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txthorario.setLabelText("HORARIO");
        txthorario.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txthorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 180, -1));

        txtdocente.setBackground(new java.awt.Color(255, 255, 255));
        txtdocente.setForeground(new java.awt.Color(51, 51, 51));
        txtdocente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtdocente.setLabelText("ID DOCENTE");
        txtdocente.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtdocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, -1));

        txtdepartamento.setBackground(new java.awt.Color(255, 255, 255));
        txtdepartamento.setForeground(new java.awt.Color(51, 51, 51));
        txtdepartamento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtdepartamento.setLabelText("ID DEPARTAMENTO");
        txtdepartamento.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 150, -1));

        txtcreditos.setBackground(new java.awt.Color(255, 255, 255));
        txtcreditos.setForeground(new java.awt.Color(51, 51, 51));
        txtcreditos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtcreditos.setLabelText("CREDITOS");
        txtcreditos.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtcreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 110, -1));

        txtrequisitos.setBackground(new java.awt.Color(255, 255, 255));
        txtrequisitos.setForeground(new java.awt.Color(51, 51, 51));
        txtrequisitos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtrequisitos.setLabelText("REQUISITOS");
        txtrequisitos.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtrequisitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 230, -1));

        txtlugar.setBackground(new java.awt.Color(255, 255, 255));
        txtlugar.setForeground(new java.awt.Color(51, 51, 51));
        txtlugar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtlugar.setLabelText("LUGAR");
        txtlugar.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        gestionarActividades ventana  = new gestionarActividades();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseClicked
        gestionarActividades ventana  = new gestionarActividades();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volver1MouseClicked

    private void volver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseEntered
        volver.setFont(new Font("Roboto", Font.PLAIN, 14));
    }//GEN-LAST:event_volver1MouseEntered

    private void volver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseExited
        volver.setFont(new Font("Roboto", Font.PLAIN, 12));
    }//GEN-LAST:event_volver1MouseExited

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        cupo= txtcupo.getText();
        clave=txtclave.getText();
        nombre=txtnombre.getText();
        horario=txthorario.getText();
        docente=txtdocente.getText();
        departamento=txtdepartamento.getText();
        creditos=txtcreditos.getText();
        requisitos=txtrequisitos.getText();
        lugar=txtlugar.getText();
        try {
            consultar.agregarActividad(clave,nombre,horario,requisitos,lugar,cupo,docente,departamento,creditos);
            limpiarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(agregarActividad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_agregarMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        cupo= txtcupo.getText();
        clave=txtclave.getText();
        nombre=txtnombre.getText();
        horario=txthorario.getText();
        docente=txtdocente.getText();
        departamento=txtdepartamento.getText();
        creditos=txtcreditos.getText();
        requisitos=txtrequisitos.getText();
        lugar=txtlugar.getText();
        try {
            consultar.modificarActividad(aux,clave,nombre,horario,requisitos,lugar,cupo,docente,departamento,creditos);
            limpiarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(agregarActividad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarMouseClicked

    public void limpiarCampos(){
        txtcupo.setText("");
        txtclave.setText("");
        txtnombre.setText("");
        txthorario.setText("");
        txtdocente.setText("");
        txtdepartamento.setText("");
        txtcreditos.setText("");
        txtrequisitos.setText("");
        txtlugar.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarActividad(clave,nombre,horario,requisitos,lugar, cupo,docente,departamento,creditos,aux).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modificar;
    private componentes.TextField txtclave;
    private componentes.TextField txtcreditos;
    private componentes.TextField txtcupo;
    private componentes.TextField txtdepartamento;
    private componentes.TextField txtdocente;
    private componentes.TextField txthorario;
    private componentes.TextField txtlugar;
    private componentes.TextField txtnombre;
    private componentes.TextField txtrequisitos;
    private javax.swing.JLabel volver;
    private javax.swing.JLabel volver1;
    // End of variables declaration//GEN-END:variables
}
