/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.consultas;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author itzim
 */
public class agregarDocentes extends javax.swing.JFrame {

    private consultas consultar;
    private gestionarDocentes metodo;
    public static String nombre,paterno,materno,correo,password,id_docente,departamento,aux,accion;
    
    public agregarDocentes(String id_docente, String nombre, String paterno, String materno, String departamento, String correo, String password, String aux) {
        initComponents();
        setLocationRelativeTo(null);
        if(metodo.accion=="agregar"){
            modificar.setVisible(false);
        }else{
            agregar.setVisible(false);
        }
        consultar = new consultas();
        metodo = new gestionarDocentes();
        this.aux=aux;
        txtid.setText(id_docente);
        txtnombre.setText(nombre);
        txtpaterno.setText(paterno);
        txtmaterno.setText(materno);
        txtdepartamento.setText(departamento);
        txtcorreo.setText(correo);
        txtcontraseña.setText(password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        volver1 = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        txtid = new componentes.TextField();
        txtcorreo = new componentes.TextField();
        txtnombre = new componentes.TextField();
        txtcontraseña = new componentes.TextField();
        txtpaterno = new componentes.TextField();
        txtmaterno = new componentes.TextField();
        txtdepartamento = new componentes.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTIONAR DOCENTES");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 900, 50));

        volver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 0, 153));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        volver1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver1.setForeground(new java.awt.Color(0, 0, 153));
        volver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver1.setText("VOLVER");
        volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volver1MouseExited(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, -1));

        agregar.setBackground(new java.awt.Color(51, 51, 255));
        agregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregar.setText("AGREGAR DOCENTE");
        agregar.setOpaque(true);
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 150, 40));

        modificar.setBackground(new java.awt.Color(51, 51, 255));
        modificar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificar.setText("MODIFICAR DATOS");
        modificar.setOpaque(true);
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 140, 40));

        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setForeground(new java.awt.Color(51, 51, 51));
        txtid.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtid.setLabelText("ID DOCENTE");
        txtid.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, -1));

        txtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtcorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtcorreo.setLabelText("CORREO");
        txtcorreo.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 250, -1));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setForeground(new java.awt.Color(51, 51, 51));
        txtnombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtnombre.setLabelText("NOMBRE");
        txtnombre.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, -1));

        txtcontraseña.setBackground(new java.awt.Color(255, 255, 255));
        txtcontraseña.setForeground(new java.awt.Color(51, 51, 51));
        txtcontraseña.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtcontraseña.setLabelText("CONTRASEÑA");
        txtcontraseña.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 220, -1));

        txtpaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtpaterno.setForeground(new java.awt.Color(51, 51, 51));
        txtpaterno.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtpaterno.setLabelText("APELLIDO PATERNO");
        txtpaterno.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtpaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 250, -1));

        txtmaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtmaterno.setForeground(new java.awt.Color(51, 51, 51));
        txtmaterno.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtmaterno.setLabelText("APELLIDO MATERNO");
        txtmaterno.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 250, -1));

        txtdepartamento.setBackground(new java.awt.Color(255, 255, 255));
        txtdepartamento.setForeground(new java.awt.Color(51, 51, 51));
        txtdepartamento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtdepartamento.setLabelText("CLAVE DEPARTAMENTO");
        txtdepartamento.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        gestionarDocentes ventana  = new gestionarDocentes();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseClicked
        gestionarDocentes ventana  = new gestionarDocentes();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volver1MouseClicked

    private void volver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseEntered
        volver.setFont(new Font("Roboto", Font.PLAIN, 14));
    }//GEN-LAST:event_volver1MouseEntered

    private void volver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseExited
        volver.setFont(new Font("Roboto", Font.PLAIN, 12));
    }//GEN-LAST:event_volver1MouseExited

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        id_docente = txtid.getText();
        nombre = txtnombre.getText();
        paterno = txtpaterno.getText();
        materno = txtmaterno.getText();
        departamento = txtdepartamento.getText();
        correo = txtcorreo.getText();
        password = txtcontraseña.getText();
        try {
            consultar.agregarDocente(id_docente,nombre, paterno, materno,departamento,correo,password);
            limpiarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(agregarDocentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_agregarMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        id_docente = txtid.getText();
        nombre = txtnombre.getText();
        paterno = txtpaterno.getText();
        materno = txtmaterno.getText();
        departamento = txtdepartamento.getText();
        correo = txtcorreo.getText();
        password = txtcontraseña.getText();
        try {
            consultar.modificarDocente(aux,id_docente,nombre, paterno, materno,departamento,correo,password);
            limpiarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(gestionarDocentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarMouseClicked

    public void limpiarCampos(){
        txtid.setText("");
        txtnombre.setText("");
        txtpaterno.setText("");
        txtmaterno.setText("");
        txtdepartamento.setText("");
        txtcorreo.setText("");
        txtcontraseña.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarDocentes(id_docente,nombre, paterno, materno,departamento,correo,password,aux).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modificar;
    private componentes.TextField txtcontraseña;
    private componentes.TextField txtcorreo;
    private componentes.TextField txtdepartamento;
    private componentes.TextField txtid;
    private componentes.TextField txtmaterno;
    private componentes.TextField txtnombre;
    private componentes.TextField txtpaterno;
    private javax.swing.JLabel volver;
    private javax.swing.JLabel volver1;
    // End of variables declaration//GEN-END:variables
}
