/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.consultas;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author itzim
 */
public class agregarAlumnos extends javax.swing.JFrame {

    private consultas consultar;
    private gestionarAlumnos metodo;
    static String nombre,paterno,materno,carrera,correo,contraseña,numero,semestre,aux;
    public agregarAlumnos(String nombre, String paterno, String materno, String carrera, String correo, String contraseña, String numero, String semestre, String aux) {
        initComponents();
        setLocationRelativeTo(null);
        if(metodo.accion=="agregar"){
            modificar.setVisible(false);
        }else{
            agregar.setVisible(false);
        }
        consultar = new consultas();
        metodo = new gestionarAlumnos();
        this.aux=aux;
        txtnumero.setText(numero);
        txtnombre.setText(nombre);
        txtpaterno.setText(paterno);
        txtmaterno.setText(materno);
        combocarrera.setSelectedItem(carrera);
        txtcorreo.setText(correo);
        txtcontrasena.setText(contraseña);
        txtsemestre.setText(semestre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        volver1 = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        combocarrera = new javax.swing.JComboBox<>();
        txtnumero = new componentes.TextField();
        txtcorreo = new componentes.TextField();
        txtnombre = new componentes.TextField();
        txtcontrasena = new componentes.TextField();
        txtpaterno = new componentes.TextField();
        txtsemestre = new componentes.TextField();
        txtmaterno = new componentes.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTIONAR ALUMNOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 880, 50));

        volver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 0, 153));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        volver1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver1.setForeground(new java.awt.Color(0, 0, 153));
        volver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver1.setText("VOLVER");
        volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volver1MouseExited(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, -1));

        agregar.setBackground(new java.awt.Color(51, 51, 255));
        agregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregar.setText("AGREGAR ALUMNO");
        agregar.setOpaque(true);
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 140, 40));

        modificar.setBackground(new java.awt.Color(51, 51, 255));
        modificar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificar.setText("MODIFICAR DATOS");
        modificar.setOpaque(true);
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 140, 40));

        combocarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "INGENIERÍA INDUSTRIAL", "INGENIERIA EN GESTIÓN EMPRESARIAL", "INGENIERÍA CIVIL", "INGENIERÍA ELÉCTRICA", "INGENIERÍA ADMINISTRACIÓN", "INGENIERÍA ELECTRÓNICA", "INGENIERÍA MECÁNICA", "INGENIERÍA QUÍMICA", "CONTADOR PÚBLICO" }));
        jPanel1.add(combocarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 350, 40));

        txtnumero.setBackground(new java.awt.Color(255, 255, 255));
        txtnumero.setForeground(new java.awt.Color(51, 51, 51));
        txtnumero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtnumero.setLabelText("NÚMERO DE CONTROL");
        txtnumero.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, -1));

        txtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtcorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtcorreo.setLabelText("CORREO");
        txtcorreo.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 260, -1));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setForeground(new java.awt.Color(51, 51, 51));
        txtnombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtnombre.setLabelText("NOMBRE (S)");
        txtnombre.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, -1));

        txtcontrasena.setBackground(new java.awt.Color(255, 255, 255));
        txtcontrasena.setForeground(new java.awt.Color(51, 51, 51));
        txtcontrasena.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtcontrasena.setLabelText("CONTRASEÑA");
        txtcontrasena.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 180, -1));

        txtpaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtpaterno.setForeground(new java.awt.Color(51, 51, 51));
        txtpaterno.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtpaterno.setLabelText("APELLIDO PATERNO");
        txtpaterno.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtpaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 250, -1));

        txtsemestre.setBackground(new java.awt.Color(255, 255, 255));
        txtsemestre.setForeground(new java.awt.Color(51, 51, 51));
        txtsemestre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtsemestre.setLabelText("SEMESTRE");
        txtsemestre.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtsemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 150, -1));

        txtmaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtmaterno.setForeground(new java.awt.Color(51, 51, 51));
        txtmaterno.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtmaterno.setLabelText("APELLIDO MATERNO");
        txtmaterno.setLineColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        gestionarAlumnos ventana  = new gestionarAlumnos();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseClicked
        gestionarAlumnos ventana  = new gestionarAlumnos();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volver1MouseClicked

    private void volver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseEntered
        volver.setFont(new Font("Roboto", Font.PLAIN, 14));
    }//GEN-LAST:event_volver1MouseEntered

    private void volver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseExited
        volver.setFont(new Font("Roboto", Font.PLAIN, 12));
    }//GEN-LAST:event_volver1MouseExited

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        numero = txtnumero.getText();
        nombre = txtnombre.getText();
        paterno = txtpaterno.getText();
        materno = txtmaterno.getText();
        carrera=combocarrera.getSelectedItem().toString();
        correo = txtcorreo.getText();
        contraseña = txtcontrasena.getText();
        semestre = txtsemestre.getText();
        
        if(numero.length()>7&&numero.length()<10){
            if(contraseña.isEmpty()){
                JOptionPane.showMessageDialog(this,"La contraseña no puede estár vacía");
            }else{
                if(contraseña.length()<8 || contraseña.length()>16||validarMayuscula(contraseña)==false||validarNumero(contraseña)==false) {
                    JOptionPane.showMessageDialog(this,"La contreña debe tener al menos ocho caracteres, una letra mayuscula y un número.");}
                else{
                    try{
                        if(!contraseña.isEmpty()&&contraseña.length()>=8&&validarMayuscula(contraseña)==true&&validarNumero(contraseña)==true&&consultar.registrarAlumno(numero,nombre,paterno,materno,carrera,Integer.parseInt(semestre),correo,contraseña)){
                            JOptionPane.showMessageDialog(this,"El usuario se ha registrado correctamente");            
                            limpiarCampos();   
                            txtnumero.setFocusable(true);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Error al crear usuario"+e);
                    }
            }}
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, verificar que el número de control sea correcto.");
        }
        
        
    }//GEN-LAST:event_agregarMouseClicked

    public static boolean validarMayuscula(String contraseña){
            Pattern upperCasePattern = Pattern.compile("[A-Z]");
            Matcher upperCaseMatcher = upperCasePattern.matcher(contraseña);
            boolean mayuscula = upperCaseMatcher.find();
            return mayuscula;
    }
    public static boolean validarNumero(String contraseña){
        Pattern numberPattern = Pattern.compile("\\d");
            Matcher numberMatcher = numberPattern.matcher(contraseña);
            boolean numero = numberMatcher.find();
            return numero;
    }
    
    public void limpiarCampos(){
        txtnumero.setText("");
        txtnombre.setText("");
        txtcorreo.setText("");
        txtcontrasena.setText("");
        txtpaterno.setText("");
        txtsemestre.setText("");
        txtmaterno.setText("");
        combocarrera.setSelectedIndex(0);
    }
    
    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        numero = txtnumero.getText();
        nombre = txtnombre.getText();
        paterno = txtpaterno.getText();
        materno = txtmaterno.getText();
        carrera=combocarrera.getSelectedItem().toString();
        correo = txtcorreo.getText();
        contraseña = txtcontrasena.getText();
        semestre = txtsemestre.getText();
        try {
            consultar.modificarAlumno(aux,numero,nombre,paterno,materno,carrera,correo,contraseña,semestre);
            limpiarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(gestionarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarAlumnos(nombre,paterno,materno,carrera,correo,contraseña,numero,semestre,aux).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JComboBox<String> combocarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modificar;
    private componentes.TextField txtcontrasena;
    private componentes.TextField txtcorreo;
    private componentes.TextField txtmaterno;
    private componentes.TextField txtnombre;
    private componentes.TextField txtnumero;
    private componentes.TextField txtpaterno;
    private componentes.TextField txtsemestre;
    private javax.swing.JLabel volver;
    private javax.swing.JLabel volver1;
    // End of variables declaration//GEN-END:variables
}
