/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.consultas;
import static Vista.login.usuario;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author itzim
 */
public class cambiarContrase extends javax.swing.JFrame {
    
    private consultas consultar;
    private login metodo;

    public cambiarContrase() {
        initComponents();
        setLocationRelativeTo(null);
        metodo = new login();
        consultar = new consultas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtactual = new componentes.PasswordField();
        cambiar = new javax.swing.JLabel();
        cancelar = new javax.swing.JLabel();
        txtNueva = new componentes.PasswordField();
        txtConfirmar = new componentes.PasswordField();
        advertencia = new javax.swing.JLabel();
        sincoincidencia = new javax.swing.JLabel();
        ojoA = new javax.swing.JLabel();
        ojoC = new javax.swing.JLabel();
        ojoN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "CAMBIAR CONTRASEÑA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Light", 1, 15), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOS CAMPOS CON * SON OBLIGATORIOS");
        jLabel1.setOpaque(true);

        txtactual.setBackground(new java.awt.Color(255, 255, 255));
        txtactual.setForeground(new java.awt.Color(51, 51, 51));
        txtactual.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtactual.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtactual.setLabelText("CONTRASEÑA ACTUAL*");
        txtactual.setLineColor(new java.awt.Color(51, 51, 51));

        cambiar.setBackground(new java.awt.Color(51, 51, 255));
        cambiar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        cambiar.setForeground(new java.awt.Color(255, 255, 255));
        cambiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambiar.setText("CAMBIAR");
        cambiar.setOpaque(true);
        cambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiarMouseClicked(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(204, 204, 204));
        cancelar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(51, 51, 51));
        cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelar.setText("CANCELAR");
        cancelar.setOpaque(true);
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        txtNueva.setBackground(new java.awt.Color(255, 255, 255));
        txtNueva.setForeground(new java.awt.Color(51, 51, 51));
        txtNueva.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNueva.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNueva.setLabelText("CONTRASEÑA NUEVA*");
        txtNueva.setLineColor(new java.awt.Color(51, 51, 51));

        txtConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirmar.setForeground(new java.awt.Color(51, 51, 51));
        txtConfirmar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtConfirmar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtConfirmar.setLabelText("CONFIRMAR CONTRASEÑA*");
        txtConfirmar.setLineColor(new java.awt.Color(51, 51, 51));

        advertencia.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        advertencia.setForeground(new java.awt.Color(255, 255, 255));
        advertencia.setText("LA NUEVA CONTRASEÑA NO COINCIDE");

        sincoincidencia.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        sincoincidencia.setForeground(new java.awt.Color(255, 255, 255));
        sincoincidencia.setText("LA CONTRASEÑA ACTUAL ES INCORRECTA");

        ojoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOjo.png"))); // NOI18N
        ojoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojoAMouseClicked(evt);
            }
        });

        ojoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOjo.png"))); // NOI18N
        ojoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojoCMouseClicked(evt);
            }
        });

        ojoN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOjo.png"))); // NOI18N
        ojoN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojoNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txtactual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(advertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sincoincidencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ojoC, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ojoN))
                    .addComponent(ojoA, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ojoA))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(sincoincidencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ojoN, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ojoC))
                .addGap(10, 10, 10)
                .addComponent(advertencia)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarMouseClicked
        try {
            consultar.validarContraseña(metodo.ncontrol,txtactual.getText(),metodo.usuario);
            if(consultar.valid==true){
                sincoincidencia.setForeground(Color.white);
                String nueva=txtNueva.getText();
                String confirmar = txtConfirmar.getText();
                System.out.println(txtNueva.getText()+" + "+txtConfirmar.getText());
                if(nueva.equals(confirmar)){
                    advertencia.setForeground(Color.white);
                    consultar.cambioPassword(metodo.ncontrol, metodo.usuario,txtNueva.getText());
                    if(usuario=="alumno"){
                        menuAlumno ventana  = new menuAlumno();   
                        ventana.setVisible(true);
                        this.dispose();                }
                    if(usuario=="docente"){
                        menuDocente ventana  = new menuDocente();   
                        //actiAdministroDocente ventana = new actiAdministroDocente();
                        ventana.setVisible(true);
                        this.dispose();                }
                }else{
                    advertencia.setForeground(Color.red);
                    limpiar();
                }
            } else {
                sincoincidencia.setForeground(Color.red);
                limpiar();
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error");
        }
    }//GEN-LAST:event_cambiarMouseClicked

    void limpiar(){
        txtactual.setText("");
        txtNueva.setText("");
        txtConfirmar.setText("");
    }
    
    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        menuAlumno ventana  = new menuAlumno();   
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    boolean a=true;
    private void ojoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoAMouseClicked
        if (a) {
            txtactual.setEchoChar((char)0); // Hace visible el texto del JPasswordField
        } else {
            txtactual.setEchoChar('*'); // Restaura el valor original del EchoChar (oculta la contraseña)
        }
        a = !a;    }//GEN-LAST:event_ojoAMouseClicked

    boolean b=true;
    private void ojoNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoNMouseClicked
        if (b) {
            txtNueva.setEchoChar((char)0); // Hace visible el texto del JPasswordField
        } else {
            txtNueva.setEchoChar('*'); // Restaura el valor original del EchoChar (oculta la contraseña)
        }
        b = !b; 
    }//GEN-LAST:event_ojoNMouseClicked

    boolean c = true;
    private void ojoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoCMouseClicked
        if (c) {
            txtConfirmar.setEchoChar((char)0); // Hace visible el texto del JPasswordField
        } else {
            txtConfirmar.setEchoChar('*'); // Restaura el valor original del EchoChar (oculta la contraseña)
        }
        c = !c; 
    }//GEN-LAST:event_ojoCMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambiarContrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambiarContrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambiarContrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambiarContrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambiarContrase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertencia;
    private javax.swing.JLabel cambiar;
    private javax.swing.JLabel cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel ojoA;
    private javax.swing.JLabel ojoC;
    private javax.swing.JLabel ojoN;
    private javax.swing.JLabel sincoincidencia;
    private componentes.PasswordField txtConfirmar;
    private componentes.PasswordField txtNueva;
    private componentes.PasswordField txtactual;
    // End of variables declaration//GEN-END:variables
}
