package Vista;

import javax.swing.*;
import javax.swing.table.*;
import Modelo.consultas;
import java.util.List;

public class EvaluarDocente extends javax.swing.JFrame {

    private consultas consultar;
    private login metodo;
    private List<String[]> studentDetails; // Para almacenar los detalles de los alumnos
    private static String claveGrupo; // Para almacenar la clave del grupo

    public EvaluarDocente(String claveGrupo) {
        initComponents();
        setLocationRelativeTo(null);
        this.claveGrupo = claveGrupo; // Inicializar claveGrupo en el constructor

        // Configurar el modelo de la tabla con las columnas necesarias
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Número de Control", "Nombre del Alumno", "Estatus"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2; // Solo la columna de estatus es editable
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 2) {
                    return String.class; // La columna de estatus es de tipo String
                }
                return String.class;
            }
        };

        tablaEvalua.setModel(model);

        // Configurar el JComboBox como editor de celda para la columna de estatus
        TableColumn estatusColumn = tablaEvalua.getColumnModel().getColumn(2);
        JComboBox<String> comboBox = new JComboBox<>(new String[]{"", "APROBADO", "NO APROBADO"});
        estatusColumn.setCellEditor(new DefaultCellEditor(comboBox));

        // Inicializar datos (si es necesario)
        cargarDatosAlumnos("claveGrupo"); // Ajusta "claveGrupo" según sea necesario
    }

    public void cargarDatosAlumnos(String claveGrupo) {
        consultas consultas = new consultas();
        List<String[]> studentDetails = consultas.detallesEstudiantesXgrupo(claveGrupo);

        DefaultTableModel model = (DefaultTableModel) tablaEvalua.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de cargar los datos

        for (String[] details : studentDetails) {
            model.addRow(new Object[]{details[0], details[1], ""}); // Número de control, nombre, estatus vacío
        }
    }


   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEvalua = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EVALUAR ALUMNOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 948, 73));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("CANCELAR OPERACIÓN");
        btnCancelar.setOpaque(true);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 180, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("TENGA EN CUENTA QUE DEBE ELEGIR UN ESTATUS PARA CADA UNO DE LOS ALUMNOS.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(51, 51, 255));
        btnGuardar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("GUARDAR CAMBIOS");
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 150, 40));

        tablaEvalua.setForeground(new java.awt.Color(51, 51, 51));
        tablaEvalua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO DE CONTROL", "NOMBRE DEL ALUMNO"
            }
        ));
        tablaEvalua.setAltoHead(30);
        tablaEvalua.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        tablaEvalua.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tablaEvalua.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tablaEvalua.setColorFilasBackgound2(new java.awt.Color(204, 204, 255));
        tablaEvalua.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tablaEvalua.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tablaEvalua.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        tablaEvalua.setColorSelBackgound(new java.awt.Color(0, 102, 255));
        tablaEvalua.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaEvalua.setFuenteFilas(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaEvalua.setFuenteFilasSelect(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tablaEvalua.setFuenteHead(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tablaEvalua.setGridColor(new java.awt.Color(51, 51, 51));
        tablaEvalua.setGrosorBordeFilas(0);
        tablaEvalua.setGrosorBordeHead(0);
        tablaEvalua.setRowHeight(30);
        tablaEvalua.getTableHeader().setResizingAllowed(false);
        tablaEvalua.getTableHeader().setReorderingAllowed(false);
        tablaEvalua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEvaluaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEvalua);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 841, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        int result = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea cancelar los cambios?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    
    private void tablaEvaluaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEvaluaMouseClicked
        int fila = tablaEvalua.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se seleccionó alumno.");
        } 
    }//GEN-LAST:event_tablaEvaluaMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        int result = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea guardar los cambios? Esta acción es irreversible.", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tablaEvalua.getModel();
            consultas consultas = new consultas();

            boolean allChecked = true;
            for (int i = 0; i < model.getRowCount(); i++) {
                String estatus = (String) model.getValueAt(i, 2);

                if (estatus == null || estatus.isEmpty()) {
                    allChecked = false;
                    break;
                }
            }

            if (!allChecked) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una opción (Aprobado o No aprobado) para todos los alumnos.");
                return;
            }

            for (int i = 0; i < model.getRowCount(); i++) {
                String numeroControl = (String) model.getValueAt(i, 0);
                String estatus = (String) model.getValueAt(i, 2);
                String estado = estatus.equals("APROBADO") ? "APROBADO" : "REPROBADO";

                consultas.actualizarEstatusAlumno(numeroControl, claveGrupo, estado);
            }

            JOptionPane.showMessageDialog(this, "Cambios guardados exitosamente.");
            this.dispose();
        }

    }//GEN-LAST:event_btnGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvaluarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvaluarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvaluarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvaluarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvaluarDocente(claveGrupo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro tablaEvalua;
    // End of variables declaration//GEN-END:variables
}
