
package Vista;
import Modelo.consultas;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

public class login extends javax.swing.JFrame {

    private consultas validar;
    public static String usuario;
    public static String ncontrol;
    
    public login() {
        initComponents();
        setLocationRelativeTo(null);
        //usuario = "alumno";   
        validar = new consultas();
        seccionA.setBorder(new LineBorder(Color.blue,2));
        ingresar.addMouseListener(new java.awt.event.MouseAdapter () {
        public void ingresarMouseClicked(java.awt.event.MouseEvent evt) {                                      
            ingresarMouseClicked(evt);
        }
        });
        txtUsuario.addActionListener((java.awt.event.ActionEvent evt) -> txtContraseña.requestFocus());
        txtContraseña.addActionListener((java.awt.event.ActionEvent evt) -> ingresarMouseClicked());
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new componentes.TextField();
        txtContraseña = new componentes.PasswordField();
        checkC = new javax.swing.JCheckBox();
        registrarse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seccionB = new javax.swing.JPanel();
        bbb = new javax.swing.JLabel();
        seccionA = new javax.swing.JPanel();
        seccionA1 = new javax.swing.JLabel();
        seccionC = new javax.swing.JPanel();
        ccc = new javax.swing.JLabel();
        ingresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISTEMA GESTOR DE ACTIVIDADES COMPLEMENTARIAS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INICIAR SESIÓN");

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsuario.setLabelText("NÚMERO DE CONTROL");
        txtUsuario.setLineColor(new java.awt.Color(51, 51, 51));
        txtUsuario.setMinimumSize(new java.awt.Dimension(7, 68));

        txtContraseña.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtContraseña.setLabelText("CONTRASEÑA");
        txtContraseña.setLineColor(new java.awt.Color(51, 51, 51));
        txtContraseña.setSelectionColor(new java.awt.Color(51, 51, 51));

        checkC.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkC.setText("MOSTRAR CONTRASEÑA");
        checkC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkCMouseClicked(evt);
            }
        });

        registrarse.setBackground(new java.awt.Color(51, 51, 255));
        registrarse.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        registrarse.setForeground(new java.awt.Color(255, 255, 255));
        registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarse.setText("REGISTRARSE");
        registrarse.setOpaque(true);
        registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarseMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconContraseña.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUsuario.png"))); // NOI18N

        seccionB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionBMouseClicked(evt);
            }
        });

        bbb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bbb.setForeground(new java.awt.Color(51, 51, 51));
        bbb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbb.setText("DOCENTE");

        javax.swing.GroupLayout seccionBLayout = new javax.swing.GroupLayout(seccionB);
        seccionB.setLayout(seccionBLayout);
        seccionBLayout.setHorizontalGroup(
            seccionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bbb, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seccionBLayout.setVerticalGroup(
            seccionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionBLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bbb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        seccionA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionAMouseClicked(evt);
            }
        });

        seccionA1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        seccionA1.setForeground(new java.awt.Color(51, 51, 51));
        seccionA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seccionA1.setText("ALUMNO");

        javax.swing.GroupLayout seccionALayout = new javax.swing.GroupLayout(seccionA);
        seccionA.setLayout(seccionALayout);
        seccionALayout.setHorizontalGroup(
            seccionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seccionA1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seccionALayout.setVerticalGroup(
            seccionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionALayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(seccionA1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        seccionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionCMouseClicked(evt);
            }
        });

        ccc.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ccc.setForeground(new java.awt.Color(51, 51, 51));
        ccc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccc.setText("ADMINISTRADOR");

        javax.swing.GroupLayout seccionCLayout = new javax.swing.GroupLayout(seccionC);
        seccionC.setLayout(seccionCLayout);
        seccionCLayout.setHorizontalGroup(
            seccionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seccionCLayout.setVerticalGroup(
            seccionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionCLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ccc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        ingresar.setBackground(new java.awt.Color(51, 51, 255));
        ingresar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresar.setText("INGRESAR");
        ingresar.setOpaque(true);
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seccionA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seccionC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seccionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(checkC)
                        .addGap(194, 194, 194))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(seccionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seccionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(seccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    boolean a = true;
    private void checkCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkCMouseClicked
        if (a) {
            txtContraseña.setEchoChar((char)0); // Hace visible el texto del JPasswordField
        } else {
            txtContraseña.setEchoChar('*'); // Restaura el valor original del EchoChar (oculta la contraseña)
        }
        a = !a;
    }//GEN-LAST:event_checkCMouseClicked
    
    private void registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseClicked
        Registro ventana  = new Registro();   
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarseMouseClicked

    private void seccionAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionAMouseClicked
        seccionA.setBorder(new LineBorder(Color.blue,2));
        seccionB.setBorder(null);
        seccionC.setBorder(null);
        txtUsuario.setLabelText("NÚMERO DE CONTROL");
        usuario = "alumno";
    }//GEN-LAST:event_seccionAMouseClicked

    private void seccionBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionBMouseClicked
        seccionA.setBorder(null);
        seccionB.setBorder(new LineBorder(Color.blue,2));
        seccionC.setBorder(null);
        txtUsuario.setLabelText("CLAVE DE TRABAJO");
        usuario = "docente";
    }//GEN-LAST:event_seccionBMouseClicked

    private void seccionCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionCMouseClicked
        seccionA.setBorder(null);
        seccionB.setBorder(null);
        seccionC.setBorder(new LineBorder(Color.blue,2));
        txtUsuario.setLabelText("CLAVE UNICA DE ACCESO");
        usuario = "administrador";
    }//GEN-LAST:event_seccionCMouseClicked

    private void ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseClicked
        ingresarMouseClicked();
    }//GEN-LAST:event_ingresarMouseClicked
   
    
    private void ingresarMouseClicked() {                                      
        if(usuario==null){
            usuario="alumno";}
        try {
            validar.validarContraseña(txtUsuario.getText(),txtContraseña.getText(),usuario);
            if(validar.valid==true){
                JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso"); 
                if(usuario=="alumno"){
                    ncontrol = txtUsuario.getText();
                    menuAlumno ventana  = new menuAlumno();   
                    ventana.setVisible(true);
                    this.dispose();
                }
                if(usuario=="docente"){
                    ncontrol = txtUsuario.getText();
                    menuDocente ventana  = new menuDocente();  
                    //actiAdministroDocente ventana = new actiAdministroDocente();
                    ventana.setVisible(true);
                    this.dispose();
                }
                if(usuario=="administrador"){
                    ncontrol = txtUsuario.getText();
                    menuAdmin ventana  = new menuAdmin();   
                    ventana.setVisible(true);
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Inicio de sesión fallido, verifique sus datos");       
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error");
        }
        System.out.println(txtUsuario.getText()+" + "+txtContraseña.getText());

    } 
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bbb;
    private javax.swing.JLabel ccc;
    private javax.swing.JCheckBox checkC;
    private javax.swing.JLabel ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel registrarse;
    private javax.swing.JPanel seccionA;
    private javax.swing.JLabel seccionA1;
    private javax.swing.JPanel seccionB;
    private javax.swing.JPanel seccionC;
    private componentes.PasswordField txtContraseña;
    private componentes.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
