package Vista;

import Modelo.consultas;
import javax.swing.JOptionPane;


public class menuDocente extends javax.swing.JFrame {

    private consultas consultar;
    private login metodo;
    
    public menuDocente() {
        initComponents();
        setLocationRelativeTo(null);
        consultar = new consultas();
        metodo = new login();
        System.out.println(""+metodo.usuario);
        consultar.saludo(metodo.ncontrol, metodo.usuario, lblsaludo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        cambiarContra = new javax.swing.JMenuItem();
        cerrarSesion = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblsaludo = new javax.swing.JLabel();
        actividadesAdministro = new javax.swing.JPanel();
        bbb = new javax.swing.JLabel();
        bbb1 = new javax.swing.JLabel();
        historialActividades = new javax.swing.JPanel();
        cccc = new javax.swing.JLabel();
        cccc2 = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();

        cambiarContra.setText("CAMBIAR CONTRASEÑA");
        cambiarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraActionPerformed(evt);
            }
        });
        jPopupMenu1.add(cambiarContra);

        cerrarSesion.setText("CERRAR SESIÓN");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jPopupMenu1.add(cerrarSesion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENÚ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblsaludo.setFont(new java.awt.Font("Roboto Light", 1, 15)); // NOI18N
        lblsaludo.setForeground(new java.awt.Color(51, 51, 51));
        lblsaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsaludo.setText("!¡");

        actividadesAdministro.setBackground(new java.awt.Color(255, 255, 255));
        actividadesAdministro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        actividadesAdministro.setForeground(new java.awt.Color(51, 51, 51));
        actividadesAdministro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actividadesAdministroMouseClicked(evt);
            }
        });

        bbb.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        bbb.setForeground(new java.awt.Color(51, 51, 51));
        bbb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbb.setText("VER ACTIVIDADES");

        bbb1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        bbb1.setForeground(new java.awt.Color(51, 51, 51));
        bbb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbb1.setText("QUE IMPARTO");

        javax.swing.GroupLayout actividadesAdministroLayout = new javax.swing.GroupLayout(actividadesAdministro);
        actividadesAdministro.setLayout(actividadesAdministroLayout);
        actividadesAdministroLayout.setHorizontalGroup(
            actividadesAdministroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actividadesAdministroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actividadesAdministroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bbb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bbb, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addContainerGap())
        );
        actividadesAdministroLayout.setVerticalGroup(
            actividadesAdministroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actividadesAdministroLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(bbb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bbb1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        historialActividades.setBackground(new java.awt.Color(255, 255, 255));
        historialActividades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        historialActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialActividadesMouseClicked(evt);
            }
        });

        cccc.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        cccc.setForeground(new java.awt.Color(51, 51, 51));
        cccc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cccc.setText("GENERAR");

        cccc2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        cccc2.setForeground(new java.awt.Color(51, 51, 51));
        cccc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cccc2.setText("ESTADISTICAS");

        javax.swing.GroupLayout historialActividadesLayout = new javax.swing.GroupLayout(historialActividades);
        historialActividades.setLayout(historialActividadesLayout);
        historialActividadesLayout.setHorizontalGroup(
            historialActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(historialActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cccc2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(cccc, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        historialActividadesLayout.setVerticalGroup(
            historialActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialActividadesLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(cccc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cccc2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(perfil)
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(actividadesAdministro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(historialActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(perfil)
                            .addComponent(lblsaludo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(historialActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actividadesAdministro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actividadesAdministroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actividadesAdministroMouseClicked
        if(0==0){
            actiAdministroDocente ventana  = new actiAdministroDocente();
            ventana.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No estas administrando ninguna actividad.");
        }
    }//GEN-LAST:event_actividadesAdministroMouseClicked

    private void historialActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialActividadesMouseClicked
        estadisticasDocente ventana  = new estadisticasDocente();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historialActividadesMouseClicked

    private void perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseEntered
        jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_perfilMouseEntered

    private void cambiarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraActionPerformed
        cambiarContrase ventana  = new cambiarContrase();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambiarContraActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        login ventana  = new login();
        ventana.setVisible(true);
        this.dispose();
        metodo.usuario="alumno";
    }//GEN-LAST:event_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actividadesAdministro;
    private javax.swing.JLabel bbb;
    private javax.swing.JLabel bbb1;
    private javax.swing.JMenuItem cambiarContra;
    private javax.swing.JLabel cccc;
    private javax.swing.JLabel cccc2;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JPanel historialActividades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblsaludo;
    private javax.swing.JLabel perfil;
    // End of variables declaration//GEN-END:variables
}
