/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.consultas;
import javax.swing.JOptionPane;

public class menuAlumno extends javax.swing.JFrame {
    
    private consultas consultar;
    private login metodo;

    
    public menuAlumno() {
        initComponents();
        setLocationRelativeTo(null);
        consultar = new consultas();
        metodo = new login();
        consultar.saludo(metodo.ncontrol, metodo.usuario, lblsaludo);
        consultar.comprobarInscrito(metodo.ncontrol);
        System.out.println("aa"+consultar.inscrito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        cambiarContra = new javax.swing.JMenuItem();
        cerrarSesion = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        perfil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblsaludo = new javax.swing.JLabel();
        seccionB = new javax.swing.JPanel();
        bbb = new javax.swing.JLabel();
        bbb1 = new javax.swing.JLabel();
        seccionA = new javax.swing.JPanel();
        cccc = new javax.swing.JLabel();
        cccc2 = new javax.swing.JLabel();
        seccionC = new javax.swing.JPanel();
        cccc1 = new javax.swing.JLabel();
        cccc3 = new javax.swing.JLabel();

        cambiarContra.setText("CAMBIAR CONTRASEÑA");
        cambiarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraActionPerformed(evt);
            }
        });
        jPopupMenu1.add(cambiarContra);

        cerrarSesion.setText("CERRAR SESIÓN");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jPopupMenu1.add(cerrarSesion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilMouseEntered(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENÚ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblsaludo.setFont(new java.awt.Font("Roboto Light", 1, 15)); // NOI18N
        lblsaludo.setForeground(new java.awt.Color(51, 51, 51));
        lblsaludo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsaludo.setText("!¡");

        seccionB.setBackground(new java.awt.Color(255, 255, 255));
        seccionB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        seccionB.setForeground(new java.awt.Color(51, 51, 51));
        seccionB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionBMouseClicked(evt);
            }
        });

        bbb.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        bbb.setForeground(new java.awt.Color(51, 51, 51));
        bbb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbb.setText("ACTIVIDAD ");

        bbb1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        bbb1.setForeground(new java.awt.Color(51, 51, 51));
        bbb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbb1.setText("ACTUAL");

        javax.swing.GroupLayout seccionBLayout = new javax.swing.GroupLayout(seccionB);
        seccionB.setLayout(seccionBLayout);
        seccionBLayout.setHorizontalGroup(
            seccionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seccionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bbb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bbb, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        seccionBLayout.setVerticalGroup(
            seccionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionBLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(bbb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bbb1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        seccionA.setBackground(new java.awt.Color(255, 255, 255));
        seccionA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        seccionA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionAMouseClicked(evt);
            }
        });

        cccc.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        cccc.setForeground(new java.awt.Color(51, 51, 51));
        cccc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cccc.setText("UNIRSE A");

        cccc2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        cccc2.setForeground(new java.awt.Color(51, 51, 51));
        cccc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cccc2.setText("ACTIVIDAD");

        javax.swing.GroupLayout seccionALayout = new javax.swing.GroupLayout(seccionA);
        seccionA.setLayout(seccionALayout);
        seccionALayout.setHorizontalGroup(
            seccionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seccionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cccc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cccc2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        seccionALayout.setVerticalGroup(
            seccionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionALayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(cccc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cccc2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        seccionC.setBackground(new java.awt.Color(255, 255, 255));
        seccionC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        seccionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionCMouseClicked(evt);
            }
        });

        cccc1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        cccc1.setForeground(new java.awt.Color(51, 51, 51));
        cccc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cccc1.setText("VER MIS");

        cccc3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        cccc3.setForeground(new java.awt.Color(51, 51, 51));
        cccc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cccc3.setText("CONSTANCIAS");

        javax.swing.GroupLayout seccionCLayout = new javax.swing.GroupLayout(seccionC);
        seccionC.setLayout(seccionCLayout);
        seccionCLayout.setHorizontalGroup(
            seccionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seccionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cccc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cccc3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        seccionCLayout.setVerticalGroup(
            seccionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionCLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(cccc1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cccc3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(perfil)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(seccionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seccionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(seccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perfil)
                            .addComponent(lblsaludo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seccionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seccionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void seccionBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionBMouseClicked
        if(consultar.inscrito==true){
            actividadActualAlumno ventana  = new actividadActualAlumno();   
            ventana.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No estas inscrito a una actividad.");
        }
    }//GEN-LAST:event_seccionBMouseClicked

    private void seccionAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionAMouseClicked
        if(consultar.inscrito==true){
            JOptionPane.showMessageDialog(null, "Ya estas inscrito a una actividad.");
        }else{
            unirseActividadAlumno ventana  = new unirseActividadAlumno();   
            ventana.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_seccionAMouseClicked

    private void seccionCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionCMouseClicked
        verConstanciasAlumno ventana  = new verConstanciasAlumno();   
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seccionCMouseClicked

    private void perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseEntered
        jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_perfilMouseEntered

    private void cambiarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraActionPerformed
        cambiarContrase ventana  = new cambiarContrase();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambiarContraActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        login ventana  = new login();   
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bbb;
    private javax.swing.JLabel bbb1;
    private javax.swing.JMenuItem cambiarContra;
    private javax.swing.JLabel cccc;
    private javax.swing.JLabel cccc1;
    private javax.swing.JLabel cccc2;
    private javax.swing.JLabel cccc3;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblsaludo;
    private javax.swing.JLabel perfil;
    private javax.swing.JPanel seccionA;
    private javax.swing.JPanel seccionB;
    private javax.swing.JPanel seccionC;
    // End of variables declaration//GEN-END:variables
}
