/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.consultas;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblsaludo = new javax.swing.JLabel();
        apem = new componentes.TextField();
        ncontrol = new componentes.TextField();
        nombre = new componentes.TextField();
        apep = new componentes.TextField();
        combocarre = new javax.swing.JComboBox<>();
        lbl = new javax.swing.JLabel();
        spiner = new javax.swing.JSpinner();
        contra = new componentes.PasswordField();
        correo = new componentes.TextField();
        registrarse = new javax.swing.JLabel();
        cancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE ALUMNOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblsaludo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblsaludo.setForeground(new java.awt.Color(51, 51, 51));
        lblsaludo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblsaludo.setText("FAVOR DE INGRESAR TUS DATOS");

        apem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        apem.setLabelText("APELLIDO MATERNO");
        apem.setLineColor(new java.awt.Color(51, 51, 51));
        apem.setMinimumSize(new java.awt.Dimension(7, 68));

        ncontrol.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ncontrol.setLabelText("NÚMERO DE CONTROL");
        ncontrol.setLineColor(new java.awt.Color(51, 51, 51));
        ncontrol.setMinimumSize(new java.awt.Dimension(7, 68));
        ncontrol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ncontrolKeyReleased(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombre.setLabelText("NOMBRE(S)");
        nombre.setLineColor(new java.awt.Color(51, 51, 51));
        nombre.setMinimumSize(new java.awt.Dimension(7, 68));

        apep.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        apep.setLabelText("APELLIDO PATERNO");
        apep.setLineColor(new java.awt.Color(51, 51, 51));
        apep.setMinimumSize(new java.awt.Dimension(7, 68));

        combocarre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "INGENIERÍA INDUSTRIAL", "INGENIERIA EN GESTIÓN EMPRESARIAL", "INGENIERÍA CIVIL", "INGENIERÍA ELÉCTRICA", "INGENIERÍA ADMINISTRACIÓN", "INGENIERÍA ELECTRÓNICA", "INGENIERÍA MECÁNICA", "INGENIERÍA QUÍMICA", "CONTADOR PÚBLICO" }));

        lbl.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(51, 51, 51));
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl.setText("SELECCIONA TU CARRERA Y SEMESTRE");

        spiner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        spiner.setToolTipText("");
        spiner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        contra.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        contra.setLabelText("CONTRASEÑA");
        contra.setLineColor(new java.awt.Color(51, 51, 51));
        contra.setSelectionColor(new java.awt.Color(51, 51, 51));

        correo.setEnabled(false);
        correo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        correo.setLabelText("CORREO ELECTRÓNICO");
        correo.setLineColor(new java.awt.Color(51, 51, 51));
        correo.setMinimumSize(new java.awt.Dimension(7, 68));

        registrarse.setBackground(new java.awt.Color(51, 51, 255));
        registrarse.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        registrarse.setForeground(new java.awt.Color(255, 255, 255));
        registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarse.setText("REGISTARSE");
        registrarse.setOpaque(true);
        registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarseMouseClicked(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(204, 204, 204));
        cancelar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(51, 51, 51));
        cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelar.setText("CANCELAR");
        cancelar.setOpaque(true);
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 639, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(combocarre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ncontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(correo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblsaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apem, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblsaludo)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ncontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combocarre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ncontrolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ncontrolKeyReleased
        correo.setText(ncontrol.getText()+"@itoaxaca.edu.mx");
    }//GEN-LAST:event_ncontrolKeyReleased

    private void registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseClicked
        consultas c = new consultas();
        String nc=ncontrol.getText();
        String name=nombre.getText();
        String carrera=combocarre.getSelectedItem().toString();
        String apema=apem.getText();
        String apepa=apep.getText();
        String correoo=correo.getText();
        String contrase=contra.getText();
        int semestre=Integer.parseInt(spiner.getValue().toString());
        if(nc.length()>7&&nc.length()<10){
            if(contrase.isEmpty()){
                JOptionPane.showMessageDialog(this,"La contraseña no puede estár vacía");
            }else{
                if(contrase.length()<8 || contrase.length()>16||validarMayuscula(contrase)==false||validarNumero(contrase)==false) {
                    JOptionPane.showMessageDialog(this,"La contreña debe tener al menos ocho caracteres, una letra mayuscula y un número.");}
                else{
                    try{
                        if(!contrase.isEmpty()&&contrase.length()>=8&&validarMayuscula(contrase)==true&&validarNumero(contrase)==true&&c.registrarAlumno(nc, name, apema, apepa, carrera , semestre, correoo, contrase)){
                            JOptionPane.showMessageDialog(this,"El usuario se ha registrado correctamente");            
                            limpiar();   
                            ncontrol.setFocusable(true);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Error al crear usuario"+e);
                    }
            }}
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, verificar que el número de control sea correcto.");
        }
    }//GEN-LAST:event_registrarseMouseClicked

    public static boolean validarMayuscula(String contraseña){
            Pattern upperCasePattern = Pattern.compile("[A-Z]");
            Matcher upperCaseMatcher = upperCasePattern.matcher(contraseña);
            boolean mayuscula = upperCaseMatcher.find();
            return mayuscula;
    }
    public static boolean validarNumero(String contraseña){
        Pattern numberPattern = Pattern.compile("\\d");
            Matcher numberMatcher = numberPattern.matcher(contraseña);
            boolean numero = numberMatcher.find();
            return numero;
    }
    
    public void limpiar(){
        ncontrol.setText("");
        nombre.setText("");
        apep.setText("");
        apem.setText("");
        correo.setText("");
        contra.setText("");
    }
    
    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        login ventana  = new login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.TextField apem;
    private componentes.TextField apep;
    private javax.swing.JLabel cancelar;
    private javax.swing.JComboBox<String> combocarre;
    private componentes.PasswordField contra;
    private componentes.TextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblsaludo;
    private componentes.TextField ncontrol;
    private componentes.TextField nombre;
    private javax.swing.JLabel registrarse;
    private javax.swing.JSpinner spiner;
    // End of variables declaration//GEN-END:variables
}
