/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.Correo;
import Controlador.documento;
import Modelo.consultas;
import java.awt.Font;
import javax.swing.JOptionPane;


public class unirseActividadAlumno extends javax.swing.JFrame {

    private consultas consultar;
    private login metodo;
    private documento documento;
    private Correo correo;
    
    public unirseActividadAlumno() {
        initComponents();
        setLocationRelativeTo(null);
        consultar = new consultas();
        consultar.mostrarActividades(actividades); 
        documento = new documento();
        correo = new Correo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblsaludo = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        incribirse = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actividades = new rojerusan.RSTableMetro();
        volver1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UNIRSE A UNA ACTIVIDAD");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 948, 73));

        lblsaludo.setFont(new java.awt.Font("Roboto Light", 1, 15)); // NOI18N
        lblsaludo.setForeground(new java.awt.Color(51, 51, 51));
        lblsaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsaludo.setText("SELECCIÓN DE ACTIVIDADES");
        jPanel1.add(lblsaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 156, 252, -1));

        volver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 0, 153));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 60, -1));

        incribirse.setBackground(new java.awt.Color(51, 51, 255));
        incribirse.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        incribirse.setForeground(new java.awt.Color(255, 255, 255));
        incribirse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incribirse.setText("INSCRIBIRSE");
        incribirse.setOpaque(true);
        incribirse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incribirseMouseClicked(evt);
            }
        });
        jPanel1.add(incribirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 120, 40));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        actividades.setBackground(new java.awt.Color(255, 255, 255));
        actividades.setForeground(new java.awt.Color(51, 51, 51));
        actividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE DE LA ACTIVIDAD", "CREDITOS", "CLAVE DE GRUPO", "HORARIO", "DOCENTE", "REQUISITOS", "CUPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        actividades.setAltoHead(30);
        actividades.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        actividades.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        actividades.setColorBordeHead(new java.awt.Color(255, 255, 255));
        actividades.setColorFilasBackgound2(new java.awt.Color(204, 204, 255));
        actividades.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        actividades.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        actividades.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        actividades.setColorSelBackgound(new java.awt.Color(0, 102, 255));
        actividades.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        actividades.setFuenteFilas(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        actividades.setFuenteFilasSelect(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        actividades.setFuenteHead(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        actividades.setGridColor(new java.awt.Color(51, 51, 51));
        actividades.setGrosorBordeFilas(0);
        actividades.setGrosorBordeHead(0);
        actividades.setRowHeight(30);
        actividades.getTableHeader().setResizingAllowed(false);
        actividades.getTableHeader().setReorderingAllowed(false);
        actividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actividadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(actividades);
        if (actividades.getColumnModel().getColumnCount() > 0) {
            actividades.getColumnModel().getColumn(0).setPreferredWidth(150);
            actividades.getColumnModel().getColumn(1).setResizable(false);
            actividades.getColumnModel().getColumn(1).setPreferredWidth(5);
            actividades.getColumnModel().getColumn(2).setResizable(false);
            actividades.getColumnModel().getColumn(2).setPreferredWidth(10);
            actividades.getColumnModel().getColumn(3).setPreferredWidth(50);
            actividades.getColumnModel().getColumn(4).setPreferredWidth(50);
            actividades.getColumnModel().getColumn(5).setPreferredWidth(40);
            actividades.getColumnModel().getColumn(6).setResizable(false);
            actividades.getColumnModel().getColumn(6).setPreferredWidth(5);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane2.setViewportView(jPanel2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 900, 260));

        volver1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver1.setForeground(new java.awt.Color(0, 0, 153));
        volver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver1.setText("VOLVER");
        volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volver1MouseExited(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        menuAlumno ventana  = new menuAlumno();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void incribirseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incribirseMouseClicked
        consultar.inscribirse(metodo.ncontrol,clave_grupo);
        consultar.inscrito=true;
        
        String userHome = System.getProperty("user.home");
        String array[] = new String[6];
        String[] actual =new String[4];
        actual=consultar.actividadActual2( login.ncontrol);
        array=consultar.seleccionarAlumno(login.ncontrol);
        documento.generar_horario(userHome+"/Downloads/Horario-"+array[0]+" "+array[1]+" "+array[2] +".pdf",login.ncontrol,array[0],array[1],array[2],array[3],Integer.parseInt(array[4]),Integer.parseInt(actual[2]),actual[0],actual[4],actual[3],actual[1]);
        correo.createEmail(array[5],userHome+"/Downloads/Horario-"+array[0]+" "+array[1]+" "+array[2] +".pdf");
        correo.sendEmail();
        
        menuAlumno ventana  = new menuAlumno();   
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_incribirseMouseClicked

    String clave_grupo;
    private void actividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actividadesMouseClicked
        int fila = actividades.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "No se seleccionó actividad.");
        } else {
            clave_grupo = (String) actividades.getValueAt(fila,2) .toString();
        }
    }//GEN-LAST:event_actividadesMouseClicked

    private void volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseClicked
        menuAlumno ventana  = new menuAlumno();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volver1MouseClicked

    private void volver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseEntered
        volver.setFont(new Font("Roboto", Font.PLAIN, 14));
    }//GEN-LAST:event_volver1MouseEntered

    private void volver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseExited
        volver.setFont(new Font("Roboto", Font.PLAIN, 12));
    }//GEN-LAST:event_volver1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unirseActividadAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unirseActividadAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unirseActividadAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unirseActividadAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unirseActividadAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro actividades;
    private javax.swing.JLabel incribirse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblsaludo;
    private javax.swing.JLabel volver;
    private javax.swing.JLabel volver1;
    // End of variables declaration//GEN-END:variables
}
