/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.documento;
import Modelo.consultas;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author itzim
 */
public class verConstanciasAlumno extends javax.swing.JFrame {

    private consultas consultar;
    private documento documento;
    private login metodo;

    public verConstanciasAlumno() {
        initComponents();
        setLocationRelativeTo(null);
        consultar = new consultas();
        documento =new documento();
        metodo = new login();
        System.out.println("noo");
        consultar.mostrarConstancias(constancias, metodo.ncontrol);
        System.out.println("sii");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        descargarConstancia = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        constancias = new rojerusan.RSTableMetro();
        volver1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MIS CONSTANCIAS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 948, 73));

        descargarConstancia.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        descargarConstancia.setForeground(new java.awt.Color(51, 51, 51));
        descargarConstancia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descargarConstancia.setText("DESCARGAR CONSTANCIA");
        descargarConstancia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        descargarConstancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descargarConstanciaMouseClicked(evt);
            }
        });
        jPanel1.add(descargarConstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 210, 34));

        volver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 0, 153));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 60, -1));

        constancias.setBackground(new java.awt.Color(255, 255, 255));
        constancias.setForeground(new java.awt.Color(51, 51, 51));
        constancias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE DE LA ACTIVIDAD", "CLAVE DE GRUPO", "CREDITOS", "PERIODO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        constancias.setAltoHead(30);
        constancias.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        constancias.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        constancias.setColorBordeHead(new java.awt.Color(255, 255, 255));
        constancias.setColorFilasBackgound2(new java.awt.Color(204, 204, 255));
        constancias.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        constancias.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        constancias.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        constancias.setColorSelBackgound(new java.awt.Color(0, 102, 255));
        constancias.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        constancias.setFuenteFilas(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        constancias.setFuenteFilasSelect(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        constancias.setFuenteHead(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        constancias.setGridColor(new java.awt.Color(51, 51, 51));
        constancias.setGrosorBordeFilas(0);
        constancias.setGrosorBordeHead(0);
        constancias.setRowHeight(30);
        constancias.getTableHeader().setResizingAllowed(false);
        constancias.getTableHeader().setReorderingAllowed(false);
        constancias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                constanciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(constancias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 880, 230));

        volver1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        volver1.setForeground(new java.awt.Color(0, 0, 153));
        volver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver1MouseClicked(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        menuAlumno ventana  = new menuAlumno();
        ventana.setVisible(true);
        this.dispose();
        consultar.inscrito=true;
    }//GEN-LAST:event_volverMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setFont(new Font("Roboto", Font.PLAIN, 14));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setFont(new Font("Roboto", Font.PLAIN, 12));
    }//GEN-LAST:event_volverMouseExited
    
    private void descargarConstanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descargarConstanciaMouseClicked
        String[] result = new String[6];
        result=consultar.constancia(login.ncontrol,clave_grupo);
        String userHome = System.getProperty("user.home");
        
        documento.generarConstancia(userHome+"/Downloads/Constancia-"+result[1]+"-"+result[5]+".pdf", result[1], result[0], result[2], result[3],result[4],result[5]);
        JOptionPane.showMessageDialog(null, "Constancia descargada correctamente");
    }//GEN-LAST:event_descargarConstanciaMouseClicked

    String clave_grupo;
    private void constanciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_constanciasMouseClicked
        int fila = constancias.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "No se seleccionó actividad.");
        } else {
            clave_grupo = (String) constancias.getValueAt(fila,1) .toString();
        }
    }//GEN-LAST:event_constanciasMouseClicked

    private void volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseClicked
        menuAlumno ventana  = new menuAlumno();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volver1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verConstanciasAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verConstanciasAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verConstanciasAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verConstanciasAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verConstanciasAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro constancias;
    private javax.swing.JLabel descargarConstancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel volver;
    private javax.swing.JLabel volver1;
    // End of variables declaration//GEN-END:variables
}
